In [160]:
import pandas as pd
import datetime

In [3]:
company = pd.read_csv('company.csv')

In [7]:
company.head(3)

분류     회사명    종목코드                   업종  \
0  코스피     두산우  000155  회사 본부 및 경영 컨설팅 서비스업   
1  코스피   한화3우B  00088K          기타 화학제품 제조업   
2  코스피  S-Oil우  010955           석유 정제품 제조업   

                                                주요제품         상장일  결산월  \
0  청주,소주,인쇄회로기판(인쇄회로용동박적층판),관련전자부품,기계 제조,판매/출판사업,...  1973-06-29  12월   
1  화약,화공품,자동선반류,공작기계 제조,전자교환기,건설,정보통신,종합무역/임직원 및 ...  1976-06-24  12월   
2                  석유제품,가스,윤활기유,윤활유,그리스,석유화학제품 제조,도매  1987-05-27  12월   

                 대표자명                         홈페이지     지역        구글코드  
0            박정원, 이재경  http://www.doosancorp.co.kr  서울특별시  KRX:000155  
1  최양수, 이태종, 김연철, 이민석  http://www.hanwhacorp.co.kr  서울특별시  KRX:00088K  
2    Othman Al-Ghamdi         http://www.s-oil.com  서울특별시  KRX:010955

In [8]:
company.tail(3)

분류    회사명    종목코드                        업종   주요제품         상장일  결산월  \
2019  코스닥  엠벤처투자  019590               신탁업 및 집합투자업  벤처캐피탈  1989-03-14  12월   
2020  코스닥  제미니투자  019570               신탁업 및 집합투자업  벤처캐피탈  1989-03-14  03월   
2021  코스닥    모헨즈  006920  시멘트, 석회, 플라스터 및 그 제품 제조업    레미콘  1989-01-05  12월   

     대표자명                       홈페이지     지역           구글코드  
2019  홍성혁      http://www.m-vc.co.kr  서울특별시  KOSDAQ:019590  
2020  정진식  http://www.geminivc.co.kr  서울특별시  KOSDAQ:019570  
2021  이기명     http://www.imohenz.com   충청남도  KOSDAQ:006920

In [11]:
type(company['회사명']) # pandas의 object == python's string

pandas.core.series.Series

In [17]:
company[['분류', '회사명', '종목코드']]

분류        회사명    종목코드
0     코스피        두산우  000155
1     코스피      한화3우B  00088K
2     코스피     S-Oil우  010955
3     코스피      LG화학우  051915
4     코스피    한국금융지주우  071055
...   ...        ...     ...
2017  코스닥     하이록코리아  013030
2018  코스닥  SBI인베스트먼트  019550
2019  코스닥      엠벤처투자  019590
2020  코스닥      제미니투자  019570
2021  코스닥        모헨즈  006920

[2022 rows x 3 columns]

In [18]:
company[['회사명', '대표자명', '지역']]

회사명                대표자명     지역
0           두산우            박정원, 이재경  서울특별시
1         한화3우B  최양수, 이태종, 김연철, 이민석  서울특별시
2        S-Oil우    Othman Al-Ghamdi  서울특별시
3         LG화학우                 박진수  서울특별시
4       한국금융지주우                 김남구  서울특별시
...         ...                 ...    ...
2017     하이록코리아     문휴건, 문창환 각자대표이사  부산광역시
2018  SBI인베스트먼트            다까하시 요시미  서울특별시
2019      엠벤처투자                 홍성혁  서울특별시
2020      제미니투자                 정진식  서울특별시
2021        모헨즈                 이기명   충청남도

[2022 rows x 3 columns]

In [22]:
company.columns

Index(['분류', '회사명', '종목코드', '업종', '주요제품', '상장일', '결산월', '대표자명', '홈페이지', '지역',
       '구글코드'],
      dtype='object')

In [31]:
ids = [1, 5, 100, 2010]
column_names = ['회사명', '종목코드']
company.loc[ids][column_names]

회사명    종목코드
1     한화3우B  00088K
5       GS우  078935
100     휴비스  079980
2010    글로본  019660

In [32]:
company.loc[ids, column_names]

회사명    종목코드
1     한화3우B  00088K
5       GS우  078935
100     휴비스  079980
2010    글로본  019660

In [35]:
# 1. len(DataFrame) == len(Series)
# 2. dtype == bool
company[company['회사명'] == '삼성전자']

분류   회사명    종목코드              업종  \
714  코스피  삼성전자  005930  통신 및 방송 장비 제조업   

                                                  주요제품         상장일  결산월  \
714  IMT2000 서비스용 동기식 기지국,교환국장비,데이터단말기,동영상휴대폰,핵심칩,반...  1975-06-11  12월   

              대표자명                  홈페이지   지역        구글코드  
714  권오현, 윤부근, 신종균  http://www.sec.co.kr  경기도  KRX:005930

In [40]:
kospi = company[company['분류'] == "코스피"]

In [41]:
kosdaq = company[company['분류'] == "코스닥"]

In [43]:
company[(company['종목코드']<'10000')&(company['지역']=='서울특별시')]


분류        회사명    종목코드                                     업종  \
0     코스피        두산우  000155                    회사 본부 및 경영 컨설팅 서비스업   
1     코스피      한화3우B  00088K                            기타 화학제품 제조업   
2     코스피     S-Oil우  010955                             석유 정제품 제조업   
3     코스피      LG화학우  051915                            기초 화학물질 제조업   
4     코스피    한국금융지주우  071055                                 기타 금융업   
...   ...        ...     ...                                    ...   
2012  코스닥   에이티넘인베스트  021080                            신탁업 및 집합투자업   
2014  코스닥       피에스텍  002230  측정, 시험, 항해, 제어 및 기타 정밀기기 제조업; 광학기기 제외   
2018  코스닥  SBI인베스트먼트  019550                            신탁업 및 집합투자업   
2019  코스닥      엠벤처투자  019590                            신탁업 및 집합투자업   
2020  코스닥      제미니투자  019570                            신탁업 및 집합투자업   

                                                   주요제품         상장일  결산월  \
0     청주,소주,인쇄회로기판(인쇄회로용동박적층판),관련전자부품,기계 제조,판매/출판사업,...  1973-06-29  12월   
1     화약,화공품,자동선반류,공작기계 제조,전자교환기,건설,정보통신,종합무역/임직원 및 ...  1976-06-24  12월   
2                     석유제품,가스,윤활기유,윤활유,그리스,석유화학제품 제조,도매  1987-05-27  12월   
3             유화/기능/합성수지,재생섬유소,산업재,리튬이온전지,평광판,PVC 제조,도매  2001-04-25  12월   
4                                                금융지주회사  2003-07-21  12월   
...                                                 ...         ...  ...   
2012                                              벤처캐피탈  1991-07-12  12월   
2014                                              자동차부품  1991-01-04  12월   
2018                                              벤처캐피탈  1989-09-06  12월   
2019                                              벤처캐피탈  1989-03-14  12월   
2020                                              벤처캐피탈  1989-03-14  03월   

                    대표자명                          홈페이지     지역           구글코드  
0               박정원, 이재경   http://www.doosancorp.co.kr  서울특별시     KRX:000155  
1     최양수, 이태종, 김연철, 이민석   http://www.hanwhacorp.co.kr  서울특별시     KRX:00088K  
2       Othman Al-Ghamdi          http://www.s-oil.com  서울특별시     KRX:010955  
3                    박진수         http://www.lgchem.com  서울특별시     KRX:051915  
4                    김남구  http://www.koreaholdings.com  서울특별시     KRX:071055  
...                  ...                           ...    ...            ...  
2012                 신기천      http://www.hanmivc.co.kr  서울특별시  KOSDAQ:021080  
2014               김 형 민        http://www.pstec.co.kr  서울특별시  KOSDAQ:002230  
2018            다까하시 요시미         http://www.sbik.co.kr  서울특별시  KOSDAQ:019550  
2019                 홍성혁         http://www.m-vc.co.kr  서울특별시  KOSDAQ:019590  
2020                 정진식     http://www.geminivc.co.kr  서울특별시  KOSDAQ:019570  

[621 rows x 11 columns]

In [44]:
# Data pre-processing
# 정형(structured) vs 비정형(unstructured) #정형은 숫자형, 비정형은 이미지,음악파일 등
company['회사명'].head(15)

0          두산우
1        한화3우B
2       S-Oil우
3        LG화학우
4      한국금융지주우
5          GS우
6     SK이노베이션우
7       코오롱인더우
8        삼성화재우
9       현대차2우B
10       삼성전기우
11       대신증권우
12      한화케미칼우
13       부국증권우
14         NaN
Name: 회사명, dtype: object

In [52]:
# Nan == Not a number ~= null
company[~company['종목코드'].isnull()] # ~ == not/reverse

분류        회사명    종목코드                        업종  \
0     코스피        두산우  000155       회사 본부 및 경영 컨설팅 서비스업   
1     코스피      한화3우B  00088K               기타 화학제품 제조업   
2     코스피     S-Oil우  010955                석유 정제품 제조업   
3     코스피      LG화학우  051915               기초 화학물질 제조업   
4     코스피    한국금융지주우  071055                    기타 금융업   
...   ...        ...     ...                       ...   
2017  코스닥     하이록코리아  013030                 1차 철강 제조업   
2018  코스닥  SBI인베스트먼트  019550               신탁업 및 집합투자업   
2019  코스닥      엠벤처투자  019590               신탁업 및 집합투자업   
2020  코스닥      제미니투자  019570               신탁업 및 집합투자업   
2021  코스닥        모헨즈  006920  시멘트, 석회, 플라스터 및 그 제품 제조업   

                                                   주요제품         상장일  결산월  \
0     청주,소주,인쇄회로기판(인쇄회로용동박적층판),관련전자부품,기계 제조,판매/출판사업,...  1973-06-29  12월   
1     화약,화공품,자동선반류,공작기계 제조,전자교환기,건설,정보통신,종합무역/임직원 및 ...  1976-06-24  12월   
2                     석유제품,가스,윤활기유,윤활유,그리스,석유화학제품 제조,도매  1987-05-27  12월   
3             유화/기능/합성수지,재생섬유소,산업재,리튬이온전지,평광판,PVC 제조,도매  2001-04-25  12월   
4                                                금융지주회사  2003-07-21  12월   
...                                                 ...         ...  ...   
2017                                               관이음쇠  1989-12-15  12월   
2018                                              벤처캐피탈  1989-09-06  12월   
2019                                              벤처캐피탈  1989-03-14  12월   
2020                                              벤처캐피탈  1989-03-14  03월   
2021                                                레미콘  1989-01-05  12월   

                    대표자명                          홈페이지     지역           구글코드  
0               박정원, 이재경   http://www.doosancorp.co.kr  서울특별시     KRX:000155  
1     최양수, 이태종, 김연철, 이민석   http://www.hanwhacorp.co.kr  서울특별시     KRX:00088K  
2       Othman Al-Ghamdi          http://www.s-oil.com  서울특별시     KRX:010955  
3                    박진수         http://www.lgchem.com  서울특별시     KRX:051915  
4                    김남구  http://www.koreaholdings.com  서울특별시     KRX:071055  
...                  ...                           ...    ...            ...  
2017     문휴건, 문창환 각자대표이사         http://www.hy-lok.com  부산광역시  KOSDAQ:013030  
2018            다까하시 요시미         http://www.sbik.co.kr  서울특별시  KOSDAQ:019550  
2019                 홍성혁         http://www.m-vc.co.kr  서울특별시  KOSDAQ:019590  
2020                 정진식     http://www.geminivc.co.kr  서울특별시  KOSDAQ:019570  
2021                 이기명        http://www.imohenz.com   충청남도  KOSDAQ:006920  

[2021 rows x 11 columns]

In [58]:
company = company[company['종목코드'].notnull()]

In [59]:
# company.dropna() Nan값 하나만 있어도 행을 다 날려버리는 메소드

In [60]:
company

분류        회사명    종목코드                        업종  \
0     코스피        두산우  000155       회사 본부 및 경영 컨설팅 서비스업   
1     코스피      한화3우B  00088K               기타 화학제품 제조업   
2     코스피     S-Oil우  010955                석유 정제품 제조업   
3     코스피      LG화학우  051915               기초 화학물질 제조업   
4     코스피    한국금융지주우  071055                    기타 금융업   
...   ...        ...     ...                       ...   
2017  코스닥     하이록코리아  013030                 1차 철강 제조업   
2018  코스닥  SBI인베스트먼트  019550               신탁업 및 집합투자업   
2019  코스닥      엠벤처투자  019590               신탁업 및 집합투자업   
2020  코스닥      제미니투자  019570               신탁업 및 집합투자업   
2021  코스닥        모헨즈  006920  시멘트, 석회, 플라스터 및 그 제품 제조업   

                                                   주요제품         상장일  결산월  \
0     청주,소주,인쇄회로기판(인쇄회로용동박적층판),관련전자부품,기계 제조,판매/출판사업,...  1973-06-29  12월   
1     화약,화공품,자동선반류,공작기계 제조,전자교환기,건설,정보통신,종합무역/임직원 및 ...  1976-06-24  12월   
2                     석유제품,가스,윤활기유,윤활유,그리스,석유화학제품 제조,도매  1987-05-27  12월   
3             유화/기능/합성수지,재생섬유소,산업재,리튬이온전지,평광판,PVC 제조,도매  2001-04-25  12월   
4                                                금융지주회사  2003-07-21  12월   
...                                                 ...         ...  ...   
2017                                               관이음쇠  1989-12-15  12월   
2018                                              벤처캐피탈  1989-09-06  12월   
2019                                              벤처캐피탈  1989-03-14  12월   
2020                                              벤처캐피탈  1989-03-14  03월   
2021                                                레미콘  1989-01-05  12월   

                    대표자명                          홈페이지     지역           구글코드  
0               박정원, 이재경   http://www.doosancorp.co.kr  서울특별시     KRX:000155  
1     최양수, 이태종, 김연철, 이민석   http://www.hanwhacorp.co.kr  서울특별시     KRX:00088K  
2       Othman Al-Ghamdi          http://www.s-oil.com  서울특별시     KRX:010955  
3                    박진수         http://www.lgchem.com  서울특별시     KRX:051915  
4                    김남구  http://www.koreaholdings.com  서울특별시     KRX:071055  
...                  ...                           ...    ...            ...  
2017     문휴건, 문창환 각자대표이사         http://www.hy-lok.com  부산광역시  KOSDAQ:013030  
2018            다까하시 요시미         http://www.sbik.co.kr  서울특별시  KOSDAQ:019550  
2019                 홍성혁         http://www.m-vc.co.kr  서울특별시  KOSDAQ:019590  
2020                 정진식     http://www.geminivc.co.kr  서울특별시  KOSDAQ:019570  
2021                 이기명        http://www.imohenz.com   충청남도  KOSDAQ:006920  

[2021 rows x 11 columns]

In [64]:
sample_name = ['한화', '한화3우B', '삼성전자', '카카오']
company[company['회사명'].isin(sample_name)]

분류    회사명    종목코드                                업종  \
1    코스피  한화3우B  00088K                       기타 화학제품 제조업   
16   코스피    카카오  035720  자료처리, 호스팅, 포털 및 기타 인터넷 정보매개 서비스업   
671  코스피     한화  000880                       기타 화학제품 제조업   
714  코스피   삼성전자  005930                    통신 및 방송 장비 제조업   

                                                  주요제품         상장일  결산월  \
1    화약,화공품,자동선반류,공작기계 제조,전자교환기,건설,정보통신,종합무역/임직원 및 ...  1976-06-24  12월   
16                                     인터넷 서비스(인터넷 광고)  2017-07-10  12월   
671  화약,화공품,자동선반류,공작기계 제조,전자교환기,건설,정보통신,종합무역/임직원 및 ...  1976-06-24  12월   
714  IMT2000 서비스용 동기식 기지국,교환국장비,데이터단말기,동영상휴대폰,핵심칩,반...  1975-06-11  12월   

                   대표자명                         홈페이지       지역        구글코드  
1    최양수, 이태종, 김연철, 이민석  http://www.hanwhacorp.co.kr    서울특별시  KRX:00088K  
16                  임지훈     http://www.kakaocorp.com  제주특별자치도  KRX:035720  
671  최양수, 이태종, 김연철, 이민석  http://www.hanwhacorp.co.kr    서울특별시  KRX:000880  
714       권오현, 윤부근, 신종균         http://www.sec.co.kr      경기도  KRX:005930

In [68]:
samsungs = company[company['회사명'].str.contains('삼성')]

In [73]:
# Quiz. 
# 위에서 배운 내용을 토대로,
# 1. 업종이 기타 금융업 이고,
# 2. 코스닥 에 상장되어 있으며,
# 3. 2015-1-1 이후에 상장된 기업정보만 필터링할 수 있습니다.

# 더불어, 날짜를 계산하는 방법으로 datetime 모듈을 사용하거나 pandas의 Timestamp 메소드를 사용하는 방법 두가지가 있습니다.

In [124]:
# 내 답안
term1 = (company['업종'] == '기타 금융업')
term2 = (company['분류'] == '코스닥')
term3 = (pd.to_datetime(company['상장일']) > pd.to_datetime('2015-1-1'))
# term3 = (pd.to_datetime(company['상장일']) > '2015-1-1') # str으로 비교됨
# term3 = (company['상장일'] > '2015-1-1')
company[ term1 & term2 & term3 ]



분류       회사명    종목코드      업종                                      주요제품  \
795  코스닥     제일홀딩스  003380  기타 금융업                                      지주사업   
844  코스닥  오가닉티코스메틱  900300  기타 금융업          유아용 화장품(클렌징, 여름용, 피부케어, 기능성 화장품)   
850  코스닥       GRT  900290  기타 금융업                                광학필름, 포장필름   
851  코스닥     골든센츄리  900280  기타 금융업                              트랙터용 휠 및 타이어   
854  코스닥     잉글우드랩  950140  기타 금융업                             기초화장품(화장품 제조)   
863  코스닥      헝셩그룹  900270  기타 금융업                   자회사 제품 : 아동용 완구 및 아동복 등   
873  코스닥       로스웰  900260  기타 금융업  CAN Control Gateway, CAN기능모듈, BCM 차체제어모듈   
894  코스닥   크리스탈신소재  900250  기타 금융업                       합성운모 플레이크, 파우더, 테이프   
935  코스닥  이베스트스팩3호  225440  기타 금융업                                       NaN   

            상장일  결산월            대표자명                               홈페이지  \
795  2017-06-30  12월             민동기          http://jeilholdings.co.kr   
844  2016-11-04  12월             채정망                                NaN   
850  2016-10-25  06월             주영남                                NaN   
851  2016-10-19  12월             주승화         http://www.jsj-wheel.co.kr   
854  2016-10-14  12월  David C. Chung        http://www.englewoodlab.com   
863  2016-08-18  12월            후이만킷                                NaN   
873  2016-06-30  12월            저우샹동                                NaN   
894  2016-01-28  12월            다이자룽  http://www.crystalnewmaterial.com   
935  2015-10-19  12월             이정훈                                NaN   

         지역           구글코드  
795    전라북도  KOSDAQ:003380  
844      홍콩  KOSDAQ:900300  
850      홍콩  KOSDAQ:900290  
851  케이맨 제도  KOSDAQ:900280  
854      미국  KOSDAQ:950140  
863      홍콩  KOSDAQ:900270  
873      홍콩  KOSDAQ:900260  
894  케이맨 제도  KOSDAQ:900250  
935   서울특별시  KOSDAQ:225440

In [114]:
type(pd.to_datetime(company['상장일']))

pandas._libs.tslibs.timestamps.Timestamp

In [111]:
# 강사님 답안
financial_corp = company[company['업종'] == '기타 금융업']
financial_corp[financial_corp['분류'] == '코스닥']

분류        회사명    종목코드      업종  \
795   코스닥      제일홀딩스  003380  기타 금융업   
844   코스닥   오가닉티코스메틱  900300  기타 금융업   
850   코스닥        GRT  900290  기타 금융업   
851   코스닥      골든센츄리  900280  기타 금융업   
854   코스닥      잉글우드랩  950140  기타 금융업   
863   코스닥       헝셩그룹  900270  기타 금융업   
873   코스닥        로스웰  900260  기타 금융업   
894   코스닥    크리스탈신소재  900250  기타 금융업   
935   코스닥   이베스트스팩3호  225440  기타 금융업   
1162  코스닥         완리  900180  기타 금융업   
1165  코스닥      골프존뉴딘  121440  기타 금융업   
1230  코스닥  이스트아시아홀딩스  900110  기타 금융업   
1233  코스닥     씨케이에이치  900120  기타 금융업   
1239  코스닥     차이나하오란  900090  기타 금융업   
1247  코스닥     글로벌에스엠  900070  기타 금융업   
1254  코스닥   에스앤씨엔진그룹  900080  기타 금융업   
1273  코스닥        게임빌  063080  기타 금융업   
1277  코스닥    차이나그레이트  900040  기타 금융업   
1297  코스닥    유비쿼스홀딩스  078070  기타 금융업   
1311  코스닥   슈프리마에이치큐  094840  기타 금융업   
1388  코스닥     휴온스글로벌  084110  기타 금융업   
1449  코스닥     덕산하이메탈  077360  기타 금융업   
1525  코스닥         오텍  067170  기타 금융업   
1529  코스닥    우리산업홀딩스  072470  기타 금융업   
1588  코스닥     홈센타홀딩스  060560  기타 금융업   
1660  코스닥     APS홀딩스  054620  기타 금융업   
1684  코스닥    아이디스홀딩스  054800  기타 금융업   
1763  코스닥      텍셀네트컴  038540  기타 금융업   
1769  코스닥      비츠로테크  042370  기타 금융업   
1770  코스닥    코아시아홀딩스  045970  기타 금융업   
1783  코스닥    네오위즈홀딩스  042420  기타 금융업   
1791  코스닥     우리기술투자  041190  기타 금융업   
1796  코스닥      이건홀딩스  039020  기타 금융업   
1807  코스닥     제이콘텐트리  036420  기타 금융업   
1824  코스닥      심텍홀딩스  036710  기타 금융업   
1863  코스닥    인터파크홀딩스  035080  기타 금융업   
1865  코스닥      매일홀딩스  005990  기타 금융업   
1889  코스닥      하림홀딩스  024660  기타 금융업   
1903  코스닥     휴맥스홀딩스  028080  기타 금융업   
1914  코스닥      원익홀딩스  030530  기타 금융업   
1917  코스닥     메이슨캐피탈  021880  기타 금융업   
1964  코스닥      한국캐피탈  023760  기타 금융업   
1980  코스닥         부방  014470  기타 금융업   
1997  코스닥       큐캐피탈  016600  기타 금융업   

                                          주요제품         상장일  결산월  \
795                                       지주사업  2017-06-30  12월   
844           유아용 화장품(클렌징, 여름용, 피부케어, 기능성 화장품)  2016-11-04  12월   
850                                 광학필름, 포장필름  2016-10-25  06월   
851                               트랙터용 휠 및 타이어  2016-10-19  12월   
854                              기초화장품(화장품 제조)  2016-10-14  12월   
863                    자회사 제품 : 아동용 완구 및 아동복 등  2016-08-18  12월   
873   CAN Control Gateway, CAN기능모듈, BCM 차체제어모듈  2016-06-30  12월   
894                        합성운모 플레이크, 파우더, 테이프  2016-01-28  12월   
935                                        NaN  2015-10-19  12월   
1162                                      외벽타일  2011-06-13  12월   
1165                                   골프시뮬레이터  2011-05-20  12월   
1230                               스포츠화, 스포츠의류  2010-04-23  12월   
1233                                    건강보조식품  2010-03-31  06월   
1239                                     코팅백판지  2010-02-05  12월   
1247    자회사 제품 : IT기기용 정밀 화스너부품(스크류, 샤프트, 스프링)  2009-12-23  12월   
1254                          오토바이, 제초기, 자동차기어  2009-12-04  12월   
1273                                     모바일게임  2009-07-30  12월   
1277                                 스포츠화 및 의류  2009-05-29  12월   
1297      소프트웨어 개발,정보처리유선,무선통신기기,부품,컴퓨터 도소매,제조  2009-01-23  12월   
1311                               지문인식솔루션및시스템  2008-07-11  12월   
1388                              비만치료제,국소마취제등  2006-12-19  12월   
1449                           솔더볼(Solderball)  2005-10-14  12월   
1525                           냉동 및 내장탑차, 앰블란스  2003-11-14  12월   
1529             HVAC ACTUATOR (자동차 공조장치 부품 등)  2003-10-28  12월   
1588                                  건축자재,레미콘  2002-07-11  12월   
1660                               인터넷 트래픽 솔루션  2001-12-04  12월   
1684                                   비금융지주회사  2001-09-27  12월   
1763                              전자계전기(RELAY)  2000-08-18  12월   
1769                                  차단기, 개폐기  2000-08-03  06월   
1770                       디지털 컨텐츠 저작솔루션 판매 사업  2000-08-03  12월   
1783                                      지주사업  2000-06-27  12월   
1791                           창업자에 대한 투자 및 융자  2000-06-09  12

In [125]:
# 자체적으로 데이터를 뽑을때 날짜를 Timestamp로 바꿈
# company = pd.read_csv('company.csv', parse_dates=['상장일'])


In [136]:
financial_corp = company[company['업종'] == '기타 금융업']
kosdaq_financial_corp = financial_corp[financial_corp['분류'] == '코스닥']
kosdaq_financial_corp['상장일'] = pd.to_datetime(kosdaq_financial_corp['상장일'])
kosdaq_financial_corp[kosdaq_financial_corp['상장일'] > pd.Timestamp(2015, 1, 1)] # '2015-1-1'로 해도 되나 나중에 연도만 따로 뽑거나 하기 힘들다. 문자로 비교하게됨.
# deprecitated: 지금은 지원하지만 조만간 바꿀꺼다.
# 아래 문법이 낫다. 하지만 무시해도 돌간다.

<ipython-input-136-1012a81e04b1>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  kosdaq_financial_corp['상장일'] = pd.to_datetime(kosdaq_financial_corp['상장일'])


분류       회사명    종목코드      업종                                      주요제품  \
795  코스닥     제일홀딩스  003380  기타 금융업                                      지주사업   
844  코스닥  오가닉티코스메틱  900300  기타 금융업          유아용 화장품(클렌징, 여름용, 피부케어, 기능성 화장품)   
850  코스닥       GRT  900290  기타 금융업                                광학필름, 포장필름   
851  코스닥     골든센츄리  900280  기타 금융업                              트랙터용 휠 및 타이어   
854  코스닥     잉글우드랩  950140  기타 금융업                             기초화장품(화장품 제조)   
863  코스닥      헝셩그룹  900270  기타 금융업                   자회사 제품 : 아동용 완구 및 아동복 등   
873  코스닥       로스웰  900260  기타 금융업  CAN Control Gateway, CAN기능모듈, BCM 차체제어모듈   
894  코스닥   크리스탈신소재  900250  기타 금융업                       합성운모 플레이크, 파우더, 테이프   
935  코스닥  이베스트스팩3호  225440  기타 금융업                                       NaN   

           상장일  결산월            대표자명                               홈페이지  \
795 2017-06-30  12월             민동기          http://jeilholdings.co.kr   
844 2016-11-04  12월             채정망                                NaN   
850 2016-10-25  06월             주영남                                NaN   
851 2016-10-19  12월             주승화         http://www.jsj-wheel.co.kr   
854 2016-10-14  12월  David C. Chung        http://www.englewoodlab.com   
863 2016-08-18  12월            후이만킷                                NaN   
873 2016-06-30  12월            저우샹동                                NaN   
894 2016-01-28  12월            다이자룽  http://www.crystalnewmaterial.com   
935 2015-10-19  12월             이정훈                                NaN   

         지역           구글코드  
795    전라북도  KOSDAQ:003380  
844      홍콩  KOSDAQ:900300  
850      홍콩  KOSDAQ:900290  
851  케이맨 제도  KOSDAQ:900280  
854      미국  KOSDAQ:950140  
863      홍콩  KOSDAQ:900270  
873      홍콩  KOSDAQ:900260  
894  케이맨 제도  KOSDAQ:900250  
935   서울특별시  KOSDAQ:225440

# Data Structure

1. Series

In [138]:
# Series는 수학적으로 벡터(vector)와 유사합니다.
odd = [1, 3, 5, 7, 9]
odd = pd.Series(odd)
type(odd)

pandas.core.series.Series

2. DataFrame

In [166]:
# DataFrame은 수학적으로 행렬과 유사합니다.
numbers = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

numbers = pd.DataFrame(numbers)

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [145]:
print(odd.dtypes)
odd

int64


0    1
1    3
2    5
3    7
4    9
dtype: int64

In [147]:
sample_odd = [1.0, 3, 5, 7, 9]
sample_odd = pd.Series(sample_odd)
sample_odd.dtypes 
sample_odd

0    1.0
1    3.0
2    5.0
3    7.0
4    9.0
dtype: float64

In [169]:
sample_odd_2 = [1, 3.0, 5, 'hi']
sample_odd_2 = pd.Series(sample_odd_2)
sample_odd_2.dtypes
sample_odd_2


0     1
1     3
2     5
3    hi
dtype: object

In [170]:
odd.astype("float")

0    1.0
1    3.0
2    5.0
3    7.0
4    9.0
dtype: float64

In [171]:
# Pandas Dataframe 만드는 첫번째 방법
transaction = [
    ['2020-01-01', 500, 'confirmed'],
    ['2020-01-03', 700, 'confirmed'],
    ['2020-01-10', 200, 'canceled'],
]

In [168]:
transaction

[['2020-01-01', 500, 'confirmed'],
 ['2020-01-03', 700, 'confirmed'],
 ['2020-01-10', 200, 'canceled']]

In [173]:
pd.DataFrame(transaction, columns=['date','price','state'])

date  price      state
0  2020-01-01    500  confirmed
1  2020-01-03    700  confirmed
2  2020-01-10    200   canceled

In [174]:
# Pandas Dataframe 만드는 두번째 방법
transaction = {
    'date': ['2020-01-01', '2020-01-03', '2020-01-10'],
    'price': [500, 700, 200],
    "state" : ['confirmed', 'confirmed', 'canceled']
}
transaction

{'date': ['2020-01-01', '2020-01-03', '2020-01-10'],
 'price': [500, 700, 200],
 'state': ['confirmed', 'confirmed', 'canceled']}

In [175]:
pd.DataFrame(transaction)

date  price      state
0  2020-01-01    500  confirmed
1  2020-01-03    700  confirmed
2  2020-01-10    200   canceled

In [186]:
# Pandas Dataframe 만드는 세번째 방법
transaction = [
    {'date': '2020-01-01', 'price':500, 'state':'confirmed'},
    {'date': '2020-01-03', 'price':700, 'state':'confirmed'},
    {'date': '2020-01-07', 'price':200, 'state':'canceled'},
    {'date': '2020-01-10', 'price':800, 'state':'confirmed'},
    {'date': '2020-01-15', 'price':900, 'state':'confirmed'},
    {'date': '2020-01-20', 'price':100, 'state':'canceled'},
]

index_list = [
    "Kang", "Kim", 'Choi', "Park", "Lee", "Yoon"
]

transaction_df = pd.DataFrame(transaction, index=index_list)

# 어떠한 작업을 하느냐에 따라서 최적의 방식이 정해진다.

In [193]:
transaction_df

date  price      state
Kang  2020-01-01    500  confirmed
Kim   2020-01-03    700  confirmed
Choi  2020-01-07    200   canceled
Park  2020-01-10    800  confirmed
Lee   2020-01-15    900  confirmed
Yoon  2020-01-20    100   canceled

In [188]:
transaction_df.columns

Index(['date', 'price', 'state'], dtype='object')

In [189]:
transaction_df.index

Index(['Kang', 'Kim', 'Choi', 'Park', 'Lee', 'Yoon'], dtype='object')

In [190]:
transaction_df.values

array([['2020-01-01', 500, 'confirmed'],
       ['2020-01-03', 700, 'confirmed'],
       ['2020-01-07', 200, 'canceled'],
       ['2020-01-10', 800, 'confirmed'],
       ['2020-01-15', 900, 'confirmed'],
       ['2020-01-20', 100, 'canceled']], dtype=object)

In [191]:
transaction_df.describe()

price
count    6.000000
mean   533.333333
std    326.598632
min    100.000000
25%    275.000000
50%    600.000000
75%    775.000000
max    900.000000

In [192]:
transaction_df.sort_index()

date  price      state
Choi  2020-01-07    200   canceled
Kang  2020-01-01    500  confirmed
Kim   2020-01-03    700  confirmed
Lee   2020-01-15    900  confirmed
Park  2020-01-10    800  confirmed
Yoon  2020-01-20    100   canceled

In [194]:
transaction_df.sort_index(ascending=False)

date  price      state
Yoon  2020-01-20    100   canceled
Park  2020-01-10    800  confirmed
Lee   2020-01-15    900  confirmed
Kim   2020-01-03    700  confirmed
Kang  2020-01-01    500  confirmed
Choi  2020-01-07    200   canceled

In [196]:
transaction_df.sort_values(by="price", ascending=False)

date  price      state
Lee   2020-01-15    900  confirmed
Park  2020-01-10    800  confirmed
Kim   2020-01-03    700  confirmed
Kang  2020-01-01    500  confirmed
Choi  2020-01-07    200   canceled
Yoon  2020-01-20    100   canceled

In [199]:
transaction_df['state'].value_counts()

confirmed    4
canceled     2
Name: state, dtype: int64

In [202]:
transaction_df['price'].mean()





533.3333333333334

In [203]:
transaction_df['price'].min()

100

In [204]:
transaction_df['price'].max()

900

In [205]:
transaction_df['price'].std()

326.5986323710904

In [206]:
transaction_df['price'].median()

600.0

In [209]:
transaction_df['prev-price'] = transaction_df['price'].shift(+1)
transaction_df['next-price'] = transaction_df['price'].shift(-1)

In [210]:
transaction_df

date  price      state  prev-price  next-price
Kang  2020-01-01    500  confirmed         NaN       700.0
Kim   2020-01-03    700  confirmed       500.0       200.0
Choi  2020-01-07    200   canceled       700.0       800.0
Park  2020-01-10    800  confirmed       200.0       900.0
Lee   2020-01-15    900  confirmed       800.0       100.0
Yoon  2020-01-20    100   canceled       900.0         NaN

In [213]:
transaction_df['diff'] = transaction_df['price'].diff()

In [214]:
transaction_df

date  price      state  prev-price  next-price   diff
Kang  2020-01-01    500  confirmed         NaN       700.0    NaN
Kim   2020-01-03    700  confirmed       500.0       200.0  200.0
Choi  2020-01-07    200   canceled       700.0       800.0 -500.0
Park  2020-01-10    800  confirmed       200.0       900.0  600.0
Lee   2020-01-15    900  confirmed       800.0       100.0  100.0
Yoon  2020-01-20    100   canceled       900.0         NaN -800.0

In [215]:
transaction_df['date']

Kang    2020-01-01
Kim     2020-01-03
Choi    2020-01-07
Park    2020-01-10
Lee     2020-01-15
Yoon    2020-01-20
Name: date, dtype: object

In [216]:
transaction_df[['date','price']]

date  price
Kang  2020-01-01    500
Kim   2020-01-03    700
Choi  2020-01-07    200
Park  2020-01-10    800
Lee   2020-01-15    900
Yoon  2020-01-20    100

In [217]:
transaction_df.loc[['Kang','Choi','Park']]

date  price      state  prev-price  next-price   diff
Kang  2020-01-01    500  confirmed         NaN       700.0    NaN
Choi  2020-01-07    200   canceled       700.0       800.0 -500.0
Park  2020-01-10    800  confirmed       200.0       900.0  600.0

In [218]:
transaction_df.loc['Kim':'Lee']

date  price      state  prev-price  next-price   diff
Kim   2020-01-03    700  confirmed       500.0       200.0  200.0
Choi  2020-01-07    200   canceled       700.0       800.0 -500.0
Park  2020-01-10    800  confirmed       200.0       900.0  600.0
Lee   2020-01-15    900  confirmed       800.0       100.0  100.0

In [219]:
transaction_df['date']['Kang'] # 느림

'2020-01-01'

In [221]:
transaction_df.loc['Kang', 'date'] # 보통, 가장 많이 쓰게 될 것.

'2020-01-01'

In [222]:
transaction_df.at['Kang', 'date'] # 가장 빠름, 단점은 데이터 하나씩 밖에 못 가져옴

'2020-01-01'

In [227]:
transaction_df.iloc[0:2]['price']

Kang    500
Kim     700
Name: price, dtype: int64

In [229]:
transaction_df.iat[1,0]

'2020-01-03'

In [230]:
transaction_df

date  price      state  prev-price  next-price   diff
Kang  2020-01-01    500  confirmed         NaN       700.0    NaN
Kim   2020-01-03    700  confirmed       500.0       200.0  200.0
Choi  2020-01-07    200   canceled       700.0       800.0 -500.0
Park  2020-01-10    800  confirmed       200.0       900.0  600.0
Lee   2020-01-15    900  confirmed       800.0       100.0  100.0
Yoon  2020-01-20    100   canceled       900.0         NaN -800.0

In [233]:
transaction_df[transaction_df['state'] == 'confirmed']

date  price      state  prev-price  next-price   diff
Kang  2020-01-01    500  confirmed         NaN       700.0    NaN
Kim   2020-01-03    700  confirmed       500.0       200.0  200.0
Park  2020-01-10    800  confirmed       200.0       900.0  600.0
Lee   2020-01-15    900  confirmed       800.0       100.0  100.0

In [234]:
transaction_df[transaction_df['state'] == 'canceled']

date  price     state  prev-price  next-price   diff
Choi  2020-01-07    200  canceled       700.0       800.0 -500.0
Yoon  2020-01-20    100  canceled       900.0         NaN -800.0

In [236]:
transaction_df[transaction_df['state'] != 'confirmed']

date  price     state  prev-price  next-price   diff
Choi  2020-01-07    200  canceled       700.0       800.0 -500.0
Yoon  2020-01-20    100  canceled       900.0         NaN -800.0

In [237]:
transaction_df[transaction_df['price'] > 600]

date  price      state  prev-price  next-price   diff
Kim   2020-01-03    700  confirmed       500.0       200.0  200.0
Park  2020-01-10    800  confirmed       200.0       900.0  600.0
Lee   2020-01-15    900  confirmed       800.0       100.0  100.0

In [245]:
def isVip(p):
    return p > 600
#transaction_df['VIP'] = transaction_df['price'] > 600
#transaction_df['VIP'] = transaction_df['price'].apply(isVip)
transaction_df['VIP'] = transaction_df['price'].apply(lambda x: x > 600) # lambda 함수 == 무명함수 == 일회용함수

In [242]:
transaction_df

date  price      state  prev-price  next-price   diff    VIP
Kang  2020-01-01    500  confirmed         NaN       700.0    NaN  False
Kim   2020-01-03    700  confirmed       500.0       200.0  200.0   True
Choi  2020-01-07    200   canceled       700.0       800.0 -500.0  False
Park  2020-01-10    800  confirmed       200.0       900.0  600.0   True
Lee   2020-01-15    900  confirmed       800.0       100.0  100.0   True
Yoon  2020-01-20    100   canceled       900.0         NaN -800.0  False

In [258]:
# 이거좀 이해가 안가네?
#transaction_df.loc[transaction_df['price'] > 600, "VIP"] = True
transaction_df.loc[transaction_df['price'] <= 600, "VIP"] = False
# transaction_df.loc["조건문","칼럼명"] 으로 받아들여라.

In [259]:
transaction_df

date  price      state  prev-price  next-price   diff    VIP
Kang  2020-01-01    500  confirmed         NaN       700.0    NaN  False
Kim   2020-01-03    700  confirmed       500.0       200.0  200.0   True
Choi  2020-01-07    200   canceled       700.0       800.0 -500.0  False
Park  2020-01-10    800  confirmed       200.0       900.0  600.0   True
Lee   2020-01-15    900  confirmed       800.0       100.0  100.0   True
Yoon  2020-01-20    100   canceled       900.0         NaN -800.0  False

In [260]:
transaction_df['card-holder'] = 'Py-Card'

In [261]:
transaction_df

date  price      state  prev-price  next-price   diff    VIP  \
Kang  2020-01-01    500  confirmed         NaN       700.0    NaN  False   
Kim   2020-01-03    700  confirmed       500.0       200.0  200.0   True   
Choi  2020-01-07    200   canceled       700.0       800.0 -500.0  False   
Park  2020-01-10    800  confirmed       200.0       900.0  600.0   True   
Lee   2020-01-15    900  confirmed       800.0       100.0  100.0   True   
Yoon  2020-01-20    100   canceled       900.0         NaN -800.0  False   

     card-holder  
Kang     Py-Card  
Kim      Py-Card  
Choi     Py-Card  
Park     Py-Card  
Lee      Py-Card  
Yoon     Py-Card

In [263]:
review_df = pd.read_csv("review.csv")

In [264]:
review_df

사용자                                                 리뷰   평점
0  김경이                   위치나 시설, 직원태도등 최근 방문한 호텔중 Best였음.   8점
1  박진형  위치도 좋고 침대가 편안해서 숙면을 취한점이 좋았습니다. 직원들도 모두 친절해서 매...   9점
2  강석민  한국인 직원이 있어서 채크인/아웃 할때 많이 편했고, 음식점 추천과 예약 등 세심하...  10점
3  최진강                   호텔이 너무 좋아서 밖으로 못나감..ㅠㅠ 정말 최고입니다.   8점

In [266]:
review_df[review_df['사용자'] == '박진형']

사용자                                                 리뷰  평점
1  박진형  위치도 좋고 침대가 편안해서 숙면을 취한점이 좋았습니다. 직원들도 모두 친절해서 매...  9점

In [268]:
user_list = ['박진형', '최진강']
review_df[review_df['사용자'].isin(user_list)]

사용자                                                 리뷰  평점
1  박진형  위치도 좋고 침대가 편안해서 숙면을 취한점이 좋았습니다. 직원들도 모두 친절해서 매...  9점
3  최진강                   호텔이 너무 좋아서 밖으로 못나감..ㅠㅠ 정말 최고입니다.  8점

In [271]:
review_df['리뷰'].str.replace("채크인",'체크인')

0                     위치나 시설, 직원태도등 최근 방문한 호텔중 Best였음.
1    위치도 좋고 침대가 편안해서 숙면을 취한점이 좋았습니다. 직원들도 모두 친절해서 매...
2    한국인 직원이 있어서 체크인/아웃 할때 많이 편했고, 음식점 추천과 예약 등 세심하...
3                     호텔이 너무 좋아서 밖으로 못나감..ㅠㅠ 정말 최고입니다.
Name: 리뷰, dtype: object

In [274]:
review_df[review_df['리뷰'].str.contains('직원')]

사용자                                                 리뷰   평점
0  김경이                   위치나 시설, 직원태도등 최근 방문한 호텔중 Best였음.   8점
1  박진형  위치도 좋고 침대가 편안해서 숙면을 취한점이 좋았습니다. 직원들도 모두 친절해서 매...   9점
2  강석민  한국인 직원이 있어서 채크인/아웃 할때 많이 편했고, 음식점 추천과 예약 등 세심하...  10점

In [285]:
review_df['리뷰'].str.split(" ")

0             [위치나, 시설,, 직원태도등, 최근, 방문한, 호텔중, Best였음.]
1    [위치도, 좋고, 침대가, 편안해서, 숙면을, 취한점이, 좋았습니다., 직원들도, ...
2    [한국인, 직원이, 있어서, 채크인/아웃, 할때, 많이, 편했고,, 음식점, 추천과...
3             [호텔이, 너무, 좋아서, 밖으로, 못나감..ㅠㅠ, 정말, 최고입니다.]
Name: 리뷰, dtype: object

In [287]:
review_df['리뷰'].str.get_dummies(sep=" ")

Best였음.  깨끗하고  너무  등  따로  룸서비스,조식  만족한  많이  매우  모두  ...  친절해서  침대가  편안해서  \
0        1     0   0  0   0        0    0   0   0   0  ...     0    0     0   
1        0     0   0  0   0        0    1   0   1   1  ...     1    1     1   
2        0     1   0  1   1        1    0   1   0   0  ...     0    0     0   
3        0     0   1  0   0        0    0   0   0   0  ...     0    0     0   

   편했고,  포함되어있지  한국인  할때  현대적입니다.  호텔이  호텔중  
0     0       0    0   0        0    0    1  
1     0       0    0   0        0    0    0  
2     1       1    1   1        1    0    0  
3     0       0    0   0        0    1    0  

[4 rows x 54 columns]

In [288]:
# 전치행렬 == transpose
review_df['리뷰'].str.get_dummies(sep=" ").transpose()

0  1  2  3
Best였음.    1  0  0  0
깨끗하고       0  0  1  0
너무         0  0  0  1
등          0  0  1  0
따로         0  0  1  0
룸서비스,조식    0  0  1  0
만족한        0  1  0  0
많이         0  0  1  0
매우         0  1  0  0
모두         0  1  0  0
못나감..ㅠㅠ    0  0  0  1
밖으로        0  0  0  1
방문한        1  0  0  0
불편함이       0  0  1  0
세심하게       0  0  1  0
숙면을        0  1  0  0
시설,        1  0  0  0
시설도        0  0  1  0
식사쿠폰이      0  0  1  0
식사하는데      0  0  1  0
신경써주셨습니다.  0  0  1  0
않지만        0  0  1  0
없었습니다.     0  0  1  0
여행이었습니다.   0  1  0  0
예약         0  0  1  0
위치나        1  0  0  0
위치도        0  1  0  0
음식점        0  0  1  0
있어서        0  0  1  0
전혀         0  0  1  0
정말         0  0  0  1
제공되어       0  0  1  0
조식은        0  0  1  0
좋고         0  1  0  0
좋아서        0  0  0  1
좋았습니다.     0  1  0  0
직원들도       0  1  0  0
직원이        0  0  1  0
직원태도등      1  0  0  0
채크인/아웃     0  0  1  0
최고입니다.     0  0  0  1
최근         1  0  0  0
추천과        0  0  1  0
취한점이       0  1  0  0
친절해서       0  1  0  0
침대가        0  1  0  0
편안해서       0  1  0  0
편했고,       0  0  1  0
포함되어있지     0  0  1  0
한국인        0  0  1  0
할때         0  0  1  0
현대적입니다.    0  0  1  0
호텔이        0  0  0  1
호텔중        1  0  0  0

In [289]:
import numpy as np

In [291]:
sample = np.array([10, 20, 30])

In [292]:
sample.shape

(3,)

In [293]:
sample.ndim

1

In [295]:
sample.dtype

dtype('int32')

In [299]:
sample_2 = [
    [1,2,3],
    [4,5,6]
]

In [303]:
sample_2 = np.array(sample_2)

In [304]:
sample_2.shape

(2, 3)

In [305]:
sample_2.ndim

2

In [308]:
sample_3 = [
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
]

sample_3 = np.array(sample_3)

In [309]:
sample_3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [310]:
sample_3.shape

(2, 2, 3)

In [311]:
sample_3.ndim

3

In [312]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [313]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [314]:
np.ones((2,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [322]:
np.full((5,3,2), 3.14)

array([[[3.14, 3.14],
        [3.14, 3.14],
        [3.14, 3.14]],

       [[3.14, 3.14],
        [3.14, 3.14],
        [3.14, 3.14]],

       [[3.14, 3.14],
        [3.14, 3.14],
        [3.14, 3.14]],

       [[3.14, 3.14],
        [3.14, 3.14],
        [3.14, 3.14]],

       [[3.14, 3.14],
        [3.14, 3.14],
        [3.14, 3.14]]])

In [324]:
np.eye(4, dtype="int")

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [327]:
np.zeros_like(sample_2).size

6

In [328]:
sample_2.astype(np.float)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [354]:
np.random.randint(0, 100, 20)

array([60, 58, 76, 11, 86, 37, 56, 37, 89, 88, 15, 80, 97, 38, 74, 86, 66,
       78, 71, 63])

In [362]:
sample_4 = np.arange(24)
sample_4.shape = (2, 3, 4)

In [363]:
sample_4

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [364]:
np.reshape(sample_4, (12, 2))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [367]:
a = np.arange(1, 10).reshape(3,3)

In [369]:
b = np.arange(9, 0, -1).reshape(3,3)

In [371]:
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


array([[0.11111111, 0.25      , 0.42857143],
       [0.66666667, 1.        , 1.5       ],
       [2.33333333, 4.        , 9.        ]])

In [372]:
a + b

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [373]:
np.add(a, b)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [374]:
a - b

array([[-8, -6, -4],
       [-2,  0,  2],
       [ 4,  6,  8]])

In [377]:
np.subtract(a, b)

array([[-8, -6, -4],
       [-2,  0,  2],
       [ 4,  6,  8]])

In [378]:
a / b

array([[0.11111111, 0.25      , 0.42857143],
       [0.66666667, 1.        , 1.5       ],
       [2.33333333, 4.        , 9.        ]])

In [379]:
np.divide(a, b)

array([[0.11111111, 0.25      , 0.42857143],
       [0.66666667, 1.        , 1.5       ],
       [2.33333333, 4.        , 9.        ]])

In [380]:
a * b

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [381]:
np.multiply(a, b)

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [382]:
a ** 2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)

In [383]:
np.square(a)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)

In [384]:
a > b

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [385]:
a == b

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

In [386]:
a != b

array([[ True,  True,  True],
       [ True, False,  True],
       [ True,  True,  True]])

In [387]:
%time np.arange(1000000)+1

Wall time: 2.99 ms


array([      1,       2,       3, ...,  999998,  999999, 1000000])

In [389]:
%time [i+1 for i in range(1000000)]

Wall time: 78.4 ms


[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185

In [390]:
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [391]:
np.tan(a)

array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501, -0.29100619],
       [ 0.87144798, -6.79971146, -0.45231566]])

In [392]:
np.cos(a)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029],
       [ 0.75390225, -0.14550003, -0.91113026]])

In [394]:
np.arange(0, 100, 20)

array([ 0, 20, 40, 60, 80])

In [395]:
np.linspace(0, 100, 20)

array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ])

In [396]:
np.random.randint(0, 100, 20)

array([61, 59, 78,  5, 50, 43, 51, 41, 66, 83, 67,  6, 41, 74, 20, 91, 13,
       98,  8, 50])

In [397]:
np.pi

3.141592653589793

In [398]:
np.sqrt(np.pi)

1.7724538509055159

In [399]:
np.power(2,4)

16

In [400]:
np.exp(2)

7.38905609893065

In [402]:
arr = np.arange(3)

In [403]:
arr

array([0, 1, 2])

In [406]:
arr+5 # 브로드캐스팅

array([5, 6, 7])

In [412]:
array = np.arange(16)

In [429]:
array = array.reshape((2,2,4))

In [430]:
array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [432]:
array[1,1,2]

14

TypeError: can only concatenate list (not "int") to list

In [433]:
array = np.arange(1,17)
array = array.reshape((4,4))

In [434]:
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [436]:
array[0:3,0:1]

array([[1],
       [5],
       [9]])

In [437]:
array[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [440]:
x = np.ones((10,10))
x[1:-1:2,1:-1:2] = 0
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])