In [1]:
%matplotlib qt5
import numpy as np
import seaborn
import matplotlib.pyplot as plt
import random

In [11]:
a = [2,4,6]
b = [1,2,3]
plt.plot(a)
plt.show()

In [13]:
a = np.random.rand(5)
print(a)
print(type(a))

[0.03272714 0.42128087 0.67570963 0.63911802 0.16477061]
<class 'numpy.ndarray'>


In [20]:
np.random.choice(3,3, replace=False)

array([0, 1, 2])

In [33]:
plt.scatter([1,2,3,4], [10,30,20,40], s=[50,100,250,400], c=range(4), cmap="gist_ncar")
plt.colorbar()
plt.show()

In [37]:
x = []
y = []
size = []
for i in range(100):
    x.append(random.randint(50,100))
    y.append(random.randint(50,100))
    size.append(random.randint(10,100))
plt.style.use('ggplot')

plt.scatter(x, y, s = size, c = size, cmap = "jet", alpha = 0.6)
plt.colorbar()

plt.show()

In [49]:
print(np.random.choice(6,10,p=[0.1,0.2,0.3,0.2,0.1,0.1]))

[5 3 4 3 3 2 1 2 2 2]


In [54]:
dice = np.random.choice(6, 100000, p =[0.1,0.2,0.3,0.2,0.1,0.1])
plt.hist(dice, bins = 6)
plt.show()

In [55]:
a = np.linspace(-np.pi, np.pi, 21)
print(a)

[-3.14159265 -2.82743339 -2.51327412 -2.19911486 -1.88495559 -1.57079633
 -1.25663706 -0.9424778  -0.62831853 -0.31415927  0.          0.31415927
  0.62831853  0.9424778   1.25663706  1.57079633  1.88495559  2.19911486
  2.51327412  2.82743339  3.14159265]


In [60]:
a = [1, 2, 3]
list(map(lambda x : x**2, a))

[1, 4, 9]

In [73]:
np.eye(5, M = 3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 0],
       [0, 0, 0]])

In [110]:
np.random.randint(1,10,1000)

array([8, 8, 4, 2, 4, 3, 3, 5, 6, 1, 4, 8, 3, 9, 1, 5, 9, 1, 2, 8, 6, 7,
       1, 3, 3, 3, 9, 9, 4, 4, 3, 9, 6, 1, 6, 5, 2, 4, 8, 5, 2, 3, 7, 7,
       6, 3, 9, 9, 5, 2, 7, 4, 4, 1, 1, 6, 8, 7, 4, 8, 2, 2, 6, 3, 8, 7,
       2, 5, 4, 8, 1, 9, 8, 6, 5, 4, 9, 3, 8, 6, 9, 3, 2, 7, 5, 5, 4, 5,
       7, 3, 9, 9, 2, 8, 1, 6, 5, 4, 6, 2, 1, 8, 8, 8, 4, 3, 7, 7, 5, 6,
       9, 5, 3, 1, 4, 7, 9, 8, 6, 9, 7, 6, 3, 1, 1, 8, 1, 5, 2, 7, 2, 7,
       1, 2, 1, 5, 5, 7, 4, 1, 2, 6, 9, 5, 6, 4, 3, 8, 1, 8, 1, 6, 5, 7,
       5, 8, 4, 6, 9, 2, 7, 3, 3, 5, 4, 9, 1, 9, 4, 5, 7, 8, 9, 7, 9, 8,
       1, 5, 6, 6, 7, 9, 1, 5, 2, 4, 3, 6, 3, 3, 4, 1, 8, 4, 7, 6, 9, 6,
       4, 1, 1, 4, 7, 3, 4, 4, 1, 3, 2, 7, 1, 1, 7, 1, 5, 1, 9, 8, 6, 4,
       4, 6, 5, 4, 7, 9, 3, 8, 1, 5, 5, 1, 6, 5, 7, 4, 1, 5, 9, 8, 3, 3,
       2, 8, 9, 3, 2, 6, 9, 4, 1, 8, 2, 8, 5, 3, 4, 3, 8, 4, 6, 2, 2, 5,
       5, 2, 7, 3, 1, 4, 6, 9, 1, 9, 1, 9, 9, 5, 3, 5, 4, 1, 4, 6, 6, 4,
       1, 2, 1, 9, 8, 3, 5, 4, 9, 2, 8, 9, 2, 4, 9,

In [94]:
x = np.random.randint(-100, 100, 1000)
y = np.random.randint(-100, 100, 1000)
mask1 = abs(x) > 50
mask2 = abs(y) > 50
x = x[mask1 + mask2]
y = y[mask1 + mask2]
size = np.random.rand(len(x)) * 100
print(len(x), len(y), len(size))
plt.scatter(x, y, s = size, c = x, cmap='jet', alpha = 0.7)

plt.show()

767 767 767


In [60]:
import csv
f = open('age.csv')
data = csv.reader(f)

data = list(data)

seoul = data[1]
myarea = []
yourarea = [] # 진관동

for row in data:
    if "남가좌제1동" in row[0]:
        for i in range(3, len(row)):
            myarea.append(int(row[i]))

for row in data:
    if "진관동" in row[0]:
        for i in range(3, len(row)):
            number = str(row[i])
            number = number.replace(",","")
            yourarea.append(int(number))
            
            
age = list(range(0,101))
result = []
for i in range(3, len(seoul)):
    number = seoul[i]
    number = number.replace(",","")
    result.append(int(number))

print(len(myarea))
    
# plt.scatter(age,result, s = 0.5)
plt.plot(age, myarea)
plt.plot(age, yourarea)
plt.show()

f.close()


101


In [44]:
a = "abcd"
a.replace("b","")

'acd'

In [69]:
import csv
f = open('age.csv')
data = csv.reader(f)
result = []
name = input("인구 구조를 알고 싶은 지역의 이름 또는 지역 코드를 입력하세요!!\n")

for row in data:
    if name in row[0]:
        for i in row[3:]:
            i = i.replace(",","")
            result.append(int(i))
            
plt.style.use('ggplot')
plt.rc('font', family="Malgun Gothic")
plt.title(name + "지역의 인구 구조")
# plt.plot(result)
plt.barh(range(101), result)
plt.show()

f.close()

인구 구조를 알고 싶은 지역의 이름 또는 지역 코드를 입력하세요!!
남가좌제1동
